### ISSUE TITLE
TypeScript error 

### ISSUE THREAD

**Issue by jimthedev** [fastify/fastify-nextjs#207] opened 2021-03-27 03:56 UTC
## 🐛 Bug Report

It is clear that that are types for fastify-nextjs and from what I can tell the types look ok with [a 'next' method being applied to fastify](https://github.com/fastify/fastify-nextjs/blob/master/index.d.ts#L20). The problem is that it is not being applied properly in my relatively simple application.

## To Reproduce

```ts
import fastify, { RequestGenericInterface } from "fastify";
import fastifyNext from 'fastify-nextjs';

const app = fastify({ logger: true })
    .register(fastifyNext)
    .after(() => {
        fastify.next('/hello')
    });

```

## Expected behavior

I expect there not to be a typescript error that says 

```
Property 'next' does not exist on type '{ <Server extends Http2SecureServer, Request extends RawRequestDefaultExpression<Server> = RawRequestDefaultExpression<Server>, Reply extends RawReplyDefaultExpression<...> = RawReplyDefaultExpression<...>, Logger extends FastifyLoggerInstance = FastifyLoggerInstance>(opts: FastifyHttp2SecureOptions<...>): FastifyIn...'.ts(2339)

```

## Your Environment

- *node version*:  12
- *fastify version*: >=2.0.0
- *os*: Mac
- ts-node

**Comment by mcollina** [comment] 2021-03-27 11:57
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Iamshankhadeep** [comment] 2021-04-17 11:02
Hey @mcollina  I want to tackle this issue. Can you guide me about what needs to be done? I could not understood how `register()` adds new function type to `fastify` instance.

**Comment by mcollina** [comment] 2021-04-18 08:29
I think if's explained in https://www.fastify.io/docs/latest/TypeScript/. cc @fastify/typescript

**Comment by Iamshankhadeep** [comment] 2021-04-18 09:52
Ahh I see thanks for the doc. It was needed. cheers. @mcollina

**Comment by KiraPC** [comment] 2021-04-22 15:24
@Iamshankhadeep 

I think there was a problem on your script.

You are referring to the fastify object not instantiated, so the error you are receiving from TS it's correct.

To make it works you need to refer to the fastify instance, that in your case it is the 'app' variable, that is an instance of type 'FastifyInstance' and has the 'next' method.

Working example based on your script.

```js
import fastify, { RequestGenericInterface } from "fastify";
import fastifyNext from 'fastify-nextjs';

const app = fastify({ logger: true })
    .register(fastifyNext)
    .after(() => {
        app.next('/hello')
    });
```

**Comment by climba03003** [comment] 2021-04-22 16:52
Closing for @KiraPC answer.

**Closed by climba03003** 2021-04-22 16:52 UTC

**Comment by Iamshankhadeep** [comment] 2021-04-22 19:59
Yeah that's true it was not a bug. Thanks for the help @KiraPC 🔥🔥
